sonar.projectKey=LaithMahdi_Mini-Project-Gestion-Retours
sonar.organization=laithmahdi

sonar.projectName=Mini-Project-Gestion-Retours
sonar.projectVersion=0.2.0
sonar.branch.name=prod

# Source paths
sonar.sources=backend/src/main,frontend/src
sonar.tests=backend/src/test

# Exclusions
sonar.exclusions=\
  **/node_modules/**,\
  **/.next/**,\
  **/target/**,\
  **/dist/**,\
  **/*.min.js

# Java bytecode for deeper analysis
sonar.java.binaries=backend/target/classes

# Coverage (optional but recommended)
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml