sonar.projectKey=mini-project-gestion-retours
sonar.projectName=Mini-Project-Gestion-Retours
sonar.sourceEncoding=UTF-8

# Monorepo sources
sonar.sources=backend/src/main,frontend/src,frontend/components,frontend/lib,frontend/config
sonar.tests=backend/src/test,frontend/src

# Exclusions
sonar.exclusions=**/node_modules/**,**/.next/**,**/target/**,**/*.min.js
sonar.test.inclusions=**/*Test.java,**/*.test.ts,**/*.test.tsx

# Java configuration
sonar.java.binaries=backend/target/classes
